import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { corsHeaders, json } from "../_shared/cors.ts";
import { supabase, addCostToLog, parseScore } from "../_shared/db.ts";
import { generateWithFallback, parseClaudeJSON } from "../_shared/api-clients.ts";
import { auditVoiceQuality } from "../_shared/voice-audit.ts";

// ---------------------------------------------------------------------------
// Senior Editor QC Prompt
// ---------------------------------------------------------------------------
const SENIOR_EDITOR_QC_PROMPT = `You are the Senior Editor of alumi news doing a FINAL quality check before publication. This is the last gate. Once you approve, this goes live to readers.

You have TWO jobs: (1) polish the headline and description, and (2) VERIFY VOICE QUALITY. This article has passed writing and independence review, but those stages don't catch blandness. YOU are the voice quality gate.

## VOICE QUALITY CHECK (read the article, then answer honestly)

You will receive a MECHANICAL VOICE AUDIT with the article. This audit is generated by code — it counts banned phrases, paragraph length, "you" usage, etc. Trust it. If the audit reports failures, those failures are REAL.

**VOICE REWRITE triggers** (if ANY of these are true AND the content/evidence is solid, decision MUST be "rewrite_voice"):
- Banned phrases found (the audit will list them)
- "you/your" count below 6
- More than 2 paragraphs exceed 3 sentences
- Zero editorial opinions (article merely explains without taking positions)
- Article reads like a Wikipedia entry or textbook — uniform sentence length, no personality, no rhythm variation
- Fails the Bill Maher test (no moment of irreverence or uncomfortable honesty)
- Doesn't follow the money (doesn't name who profits)
A "rewrite_voice" decision sends the article to our BEST models (Opus/Sonnet) for a voice-only rewrite. The facts stay — only the prose gets personality. USE THIS LIBERALLY. A boring article with good facts is fixable. Don't kill fixable articles.

**Content REVISE triggers** (decision = "revise" — sends back to full rewrite):
- Factual/structural problems, wrong angle, missing evidence, bad citations
- Content is fundamentally flawed, not just bland

**Auto-kill trigger** (decision MUST be "kill"):
- 3+ banned phrases AND zero editorial opinion → this is AI slop, not journalism
- Topic is unsalvageable or evidence is too thin

**Manual voice check** (you assess these yourself):
- Does the article pass the Bill Maher test? Is there at least ONE moment of irreverence, controlled anger, or uncomfortable honesty that a hospital pamphlet would never include?
- Does the article follow the money? Does it name who profits from the status quo?
- Are the pull quotes striking, or do they read like abstracts?
- Would a reader of The Atlantic keep reading past paragraph 3, or would they bounce?

If the voice fails but the content is solid, decision = "rewrite_voice" — NOT "revise". Voice problems are fixed by the voice rewriter, not by regenerating the whole article.

## Headline Rules
- Must be specific and honest. Prefer direct claims, mechanisms, questions, or understated phrasing
- BANNED: headlines starting with "The", "Nobody/Science/Medicine [dramatic verb]" framing, two-sentence dramatic kickers
- If the current headline is good, KEEP IT. Don't change for the sake of changing
- Rewrite ONLY if you can genuinely improve it

## Description Rules
- 2-3 sentences that make a reader stop scrolling. Must be COMPLETE sentences (no truncation)
- No clickbait, no "you won't believe" energy
- Must accurately represent the article's content and angle

## Quality Score (be honest — voice quality heavily weighted)
- 9-10: Exceptional — strong voice, clear opinions, would be proud to publish in any magazine
- 7-8: Strong — solid journalism, clear voice, well-supported claims, has edge
- 5-6: Adequate — content is fine but reads like a health blog, not alumi news. Missing personality, opinion, or follow-the-money. SHOULD TRIGGER REVISE.
- 3-4: Weak — AI slop. No voice, no opinion, banned phrases present. SHOULD TRIGGER KILL.
Score honestly. An article that merely conveys accurate information without personality or editorial opinion is a 5, not a 7.

## Output Format
Return ONLY valid JSON:
{
  "decision": "publish" | "rewrite_voice" | "revise" | "kill",
  "qualityScore": "(integer 1-10, see scoring guide above)",
  "headline": "Final headline (keep original if good enough)",
  "description": "Final description — MUST be complete sentences, never truncated",
  "voiceCheck": {
    "billMaherTest": true/false,
    "followsTheMoney": true/false,
    "hasEditorialOpinion": true/false,
    "pullQuotesStrong": true/false,
    "overallVoicePass": true/false
  },
  "edits": {
    "headlineChanged": false,
    "descriptionChanged": false,
    "notes": "What you changed and why — or 'No changes needed' if originals are strong"
  },
  "killReason": null,
  "reviseInstructions": null
}`;

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  let parsedLogId: string | null = null;
  try {
    const { logId } = await req.json();
    parsedLogId = logId;
    if (!logId) return json({ error: "logId is required" }, 400);

    const db = supabase();

    // Atomic CAS: claim this article. Only ONE instance can transition independence_done → editor_qc.
    const { data: claimed } = await db
      .from("daily_article_log")
      .update({ status: "editor_qc", stage_started_at: new Date().toISOString() })
      .eq("id", logId)
      .eq("status", "independence_done")
      .select("id")
      .maybeSingle();

    if (!claimed) {
      return json({ skipped: true, logId, message: "Another instance already claimed this article" });
    }

    // Fetch log entry with article data (CAS already claimed it)
    const { data: logEntry } = await db.from("daily_article_log").select("slug, research_data").eq("id", logId).maybeSingle();
    if (!logEntry) return json({ error: "Log entry not found" }, 404);

    const researchData = (logEntry.research_data as Record<string, unknown>) || {};
    const articleData = (researchData._article as Record<string, unknown>) || {};
    const metadata = (articleData.metadata as Record<string, unknown>) || {};
    const slug = logEntry.slug || (metadata.slug as string);
    const independenceReview = (researchData._independenceReview as Record<string, unknown>) || null;

    if (!slug) return json({ error: "No slug found in log entry" }, 400);

    // Build independence review section for QC prompt
    let independenceSection = "";
    if (independenceReview && !independenceReview.skipped) {
      const flags = (independenceReview.flags as Array<Record<string, string>>) || [];
      if (flags.length > 0) {
        independenceSection = `\n## INDEPENDENCE REVIEW (external reviewer)
Verdict: ${independenceReview.verdict}
Summary: ${independenceReview.summary}
Flags:
${flags.map((f) => `- [${f.type}] "${f.quote}" — Rewrite: ${f.rewrite || f.suggestion || "no suggestion"} (Reason: ${f.reason || "not stated"})`).join("\n")}

Consider these flags in your review. Address any legitimate concerns.\n`;
      } else {
        independenceSection = `\n## INDEPENDENCE REVIEW: Clean — no flags raised.\n`;
      }
    }

    // Run mechanical voice audit — code, not AI
    const voiceAudit = auditVoiceQuality((articleData.html as string) || "");
    const voiceAuditSection = `\n## MECHANICAL VOICE AUDIT (generated by code — these are facts, not opinions)
${voiceAudit.passed ? "✅ ALL CHECKS PASSED" : "❌ FAILURES DETECTED:"}
${voiceAudit.failures.map(f => `- ❌ ${f}`).join("\n")}

Metrics:
- Word count: ${voiceAudit.wordCount}
- Paragraphs: ${voiceAudit.totalParagraphs}
- "you/your" count: ${voiceAudit.youCount} (minimum: 6)
- Paragraphs over 3 sentences: ${voiceAudit.paragraphsOver3Sentences}
- Longest paragraph: ${voiceAudit.longestParagraphSentences} sentences
- Short sentences (< 8 words): ${voiceAudit.shortSentenceCount} (${voiceAudit.shortSentenceRatio})
- Rhetorical questions: ${voiceAudit.rhetoricQuestionCount} (max: 2)
- Banned phrases: ${voiceAudit.bannedPhrases.length > 0 ? voiceAudit.bannedPhrases.map(p => `"${p}"`).join(", ") : "none"}

${!voiceAudit.passed ? "⚠️ This article has mechanical voice failures. You MUST factor these into your decision. Banned phrases and low 'you' count are auto-revise triggers per your editorial policy." : ""}\n`;

    // Senior Editor QC pass
    const qcPrompt = `Review this article before publication.

## ARTICLE
Title: ${metadata.title}
Description: ${metadata.description}
Category: ${metadata.category}
Word count: ~${voiceAudit.wordCount}
${voiceAuditSection}
## FULL ARTICLE HTML:
${(articleData.html as string) || ""}

## TABLE OF CONTENTS
${((articleData.toc as Array<{ title: string }>) || []).map((t) => `- ${t.title}`).join("\n")}
${independenceSection}
Make your final call. Publish, request revisions, or kill. Remember: voice failures from the mechanical audit are auto-revise triggers.`;

    // QC uses a DIFFERENT model from independence review (Grok).
    // Gemini primary for QC — fast, cheap, good at headline/description polish.
    // Falls back to Sonnet if Gemini fails. Never Grok — already reviewed.
    // webSearch: false — QC analyzes the article text, doesn't need web search
    // QC is a structured pass/fail decision — mechanical voice audit does most of the work,
    // QC just reads the metrics and makes the call. Flash handles this well at 15x cheaper.
    const { text: qcRaw, usage: qcUsage } = await generateWithFallback({
      system: SENIOR_EDITOR_QC_PROMPT + `\n\nCRITICAL: Return ONLY valid JSON. No markdown, no explanation — just the JSON object.`,
      user: qcPrompt,
      models: ["gemini-2.5-flash", "claude-sonnet-4-6"], // Flash primary ($0.002), Sonnet fallback ($0.03)
      maxTokens: 2000,
      temperature: 0.3,
      stage: "qc",
      webSearch: false,
    });
    await addCostToLog(db, logId, qcUsage);

    const qcResult = parseClaudeJSON(qcRaw) as Record<string, unknown>;

    // DEFAULT-DENY: if decision is missing or unrecognized, treat as rewrite_voice (not silent publish)
    const qcDecision = qcResult.decision as string;
    if (!qcDecision || !["publish", "rewrite_voice", "revise", "kill"].includes(qcDecision)) {
      console.warn(`[QC] ⚠️ Invalid/missing decision: "${qcDecision}" — treating as rewrite_voice (default-deny). Raw QC output may be truncated.`);
      qcResult.decision = "rewrite_voice";
      qcResult.reviseInstructions = "QC output was truncated or invalid. Voice rewrite requested as safety fallback.";
    }

    // If editor kills the article, mark as failed
    if (qcResult.decision === "kill") {
      await db.from("articles").update({ status: "archived", draft: true }).eq("slug", slug);
      await db
        .from("daily_article_log")
        .update({
          status: "failed",
          error: `Senior Editor QC killed: ${qcResult.killReason || "Quality standards not met"}`,
          completed_at: new Date().toISOString(),
        })
        .eq("id", logId);
      return json({ success: true, logId, qcResult, decision: "kill" });
    }

    // If editor requests revisions, send back to write stage (max 1 revision to avoid loops)
    if (qcResult.decision === "revise") {
      const currentLog = (await db.from("daily_article_log").select("research_data, revision_count").eq("id", logId).single()).data as { research_data: Record<string, unknown>; revision_count: number | null } | null;
      const currentData = (currentLog?.research_data as Record<string, unknown>) || {};
      const revisionCount = ((currentLog?.revision_count as number) || 0) + 1;

      if (revisionCount > 1) {
        // Max revisions reached — force publish with editor's improvements applied
        console.log(`[QC] Max revisions (${revisionCount}) reached for ${slug} — force publishing`);
        // Apply headline/description improvements and set to qc_approved
        const finalTitle = (qcResult.headline as string) || (metadata.title as string);
        const finalDescription = (qcResult.description as string) || (metadata.description as string);
        if (finalTitle) (metadata as Record<string, unknown>).title = finalTitle;
        if (finalDescription) (metadata as Record<string, unknown>).description = finalDescription;
        await db.from("daily_article_log").update({
          status: "qc_approved",
          editor_score: parseScore(qcResult.qualityScore),
          research_data: {
            ...currentData,
            _article: articleData,
            _qcResult: qcResult,
          },
        }).eq("id", logId);
        return json({ success: true, logId, qcResult, decision: "publish_forced_max_revisions" });
      } else {
        await db
          .from("daily_article_log")
          .update({
            status: "editor_approved", // Back to write queue
            revision_count: revisionCount,
            research_data: {
              ...currentData,
              _reviseInstructions: qcResult.reviseInstructions,
            },
          })
          .eq("id", logId);
        // Produce handler loop will pick up editor_approved → write again
        return json({ success: true, logId, qcResult, decision: "revise" });
      }
    }

    // If voice needs rewriting, send to voice rewrite stage (max 1 voice rewrite)
    // EXCEPTION: human-written articles (Opus via Max) skip voice rewrite — never degrade Opus prose with a lesser model
    const isHumanWritten = researchData._writtenBy === "human-opus";
    if (qcResult.decision === "rewrite_voice" && isHumanWritten) {
      console.log(`[QC] Voice rewrite requested but article was human-written with Opus — skipping, publishing directly`);
      qcResult.decision = "publish";
    }
    if (qcResult.decision === "rewrite_voice") {
      const currentLog = (await db.from("daily_article_log").select("research_data, revision_count").eq("id", logId).single()).data as { research_data: Record<string, unknown>; revision_count: number | null } | null;
      const currentData = (currentLog?.research_data as Record<string, unknown>) || {};
      const voiceRewriteCount = (currentData._voiceRewriteCount as number) || 0;

      if (voiceRewriteCount > 0) {
        // Already voice-rewritten once — force publish
        console.log(`[QC] Voice rewrite already applied for ${slug} — force publishing`);
        // Apply headline/description improvements and set to qc_approved
        const finalTitle = (qcResult.headline as string) || (metadata.title as string);
        const finalDescription = (qcResult.description as string) || (metadata.description as string);
        if (finalTitle) (metadata as Record<string, unknown>).title = finalTitle;
        if (finalDescription) (metadata as Record<string, unknown>).description = finalDescription;
        await db.from("daily_article_log").update({
          status: "qc_approved",
          editor_score: parseScore(qcResult.qualityScore),
          research_data: {
            ...currentData,
            _article: articleData,
            _qcResult: qcResult,
          },
        }).eq("id", logId);
        return json({ success: true, logId, qcResult, decision: "publish_forced_already_rewritten" });
      } else {
        const { error: updateErr } = await db.from("daily_article_log").update({
          status: "voice_rewrite_pending",
          research_data: {
            ...currentData,
            _qcResult: qcResult,
            _voiceRewriteRequested: true,
            _voiceRewriteCount: 1,
          },
        }).eq("id", logId);
        if (updateErr) {
          console.error(`[stage-qc] DB update failed for voice_rewrite_pending: ${updateErr.message}`);
          return json({ error: `DB update failed: ${updateErr.message}`, logId }, 500);
        }
        return json({ success: true, logId, qcResult, decision: "rewrite_voice" });
      }
    }

    // Decision is "publish" — apply headline/description improvements, set to qc_approved
    const finalTitle = (qcResult.headline as string) || (metadata.title as string);
    const finalDescription = (qcResult.description as string) || (metadata.description as string);
    if (finalTitle) (metadata as Record<string, unknown>).title = finalTitle;
    if (finalDescription) (metadata as Record<string, unknown>).description = finalDescription;

    const { error: publishErr } = await db.from("daily_article_log").update({
      status: "qc_approved",
      editor_score: parseScore(qcResult.qualityScore),
      research_data: {
        ...researchData,
        _article: articleData,
        _qcResult: qcResult,
      },
    }).eq("id", logId);
    if (publishErr) {
      console.error(`[stage-qc] DB update failed for qc_approved: ${publishErr.message}`);
      return json({ error: `DB update failed: ${publishErr.message}`, logId }, 500);
    }

    return json({ success: true, logId, qcResult, decision: "publish" });
  } catch (err: unknown) {
    // Mark as failed so stale detection doesn't loop on it
    try {
      const db = supabase();
      const msg = err instanceof Error ? err.message : "Unknown error";
      console.error(`[stage-qc] Error: ${msg}`);
      if (parsedLogId) {
        await db.from("daily_article_log").update({
          status: "failed",
          error: `QC stage error: ${msg}`,
          completed_at: new Date().toISOString(),
        }).eq("id", parsedLogId);
      }
    } catch { /* best effort */ }
    return json({ error: err instanceof Error ? err.message : "Unknown error" }, 500);
  }
});
